---
{{ if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth.fullname" . }}-password
stringData:
  password: |
{{ .Values.password | indent 4 }}
{{- end }}

---
{{ if .Values.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth.fullname" . }}-key
stringData:
  key.json: |
{{ .Values.key | indent 4 }}
{{- end }}

---
{{ if .Values.import.ossutil.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth.fullname" . }}-ossutilconfig
type: Opaque
stringData:
  .ossutilconfig: |-
{{ .Values.import.ossutil.config | indent 4}}
{{- end }}
