apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.netwarps.com/v1alpha1",
          "kind": "Geth",
          "metadata": {
            "name": "geth-sample"
          },
          "spec": {
            "affinity": {},
            "autoscaling": {
              "enabled": false,
              "maxReplicas": 100,
              "minReplicas": 1,
              "targetCPUUtilizationPercentage": 80
            },
            "cluster": "jyliu",
            "config": "[Eth]\nNetworkId = 1\n",
            "container": {
              "ports": {
                "discovery": 30303,
                "http": 8545,
                "listener": 30303,
                "prometheus": 6060,
                "ws": 8546
              }
            },
            "env": {},
            "fullnameOverride": "",
            "genesis": "",
            "image": {
              "args": [
                "--config",
                "/root/config/config.custom.toml"
              ],
              "command": [
                "geth"
              ],
              "pullPolicy": "IfNotPresent",
              "repository": "ethereum/client-go",
              "tag": "v1.10.17"
            },
            "imagePullSecrets": [],
            "import": {
              "ossutil": {
                "bucket": "geth-backup",
                "config": "[Credentials]\nlanguage=CH\nendpoint=\"\"\naccessKeyID=\"\"\naccessKeySecret=\"\"\n",
                "enabled": false,
                "image": "quay.io/ss75710541/ossutil",
                "pullPolicy": "IfNotPresent",
                "subPath": "",
                "tag": "v1.7.13-1"
              }
            },
            "initContainer": {
              "args": [
                "init",
                "/root/config/genesis.custom.json"
              ],
              "command": [
                "geth"
              ]
            },
            "key": "",
            "nameOverride": "",
            "nodeSelector": {
              "geth/role": "node"
            },
            "password": "",
            "persistence": {
              "accessModes": [
                "ReadWriteOnce"
              ],
              "annotations": {},
              "enabled": true,
              "size": "20Gi"
            },
            "podAnnotations": {},
            "podSecurityContext": {},
            "prometheus": false,
            "replicaCount": 1,
            "resources": {},
            "securityContext": {},
            "service": {
              "http": 8545,
              "prometheus": 6060,
              "type": "ClusterIP",
              "ws": 8546
            },
            "serviceAccount": {
              "annotations": {},
              "create": false,
              "name": ""
            },
            "serviceP2P": {
              "discovery": 30303,
              "listener": 30303,
              "type": "NodePort"
            },
            "tolerations": [],
            "volumes": {
              "config": {
                "mountPath": "/root/config"
              },
              "data": {
                "mountPath": "/root/.ethereum"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.22.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: geth-helm-operator.v0.0.19
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Geth
      name: geths.charts.netwarps.com
      version: v1alpha1
  description: geth helm operator
  displayName: geth-helm-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - charts.netwarps.com
          resources:
          - geths
          - geths/status
          - geths/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: geth-helm-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: geth-helm-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.dockerproxy.com/kubebuilder/kube-rbac-proxy:v0.11.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=geth-helm-operator
                image: registry.hisun.netwarps.com/geth/geth-helm-operator:v0.0.19
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: "1"
                    memory: 512Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: geth-helm-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: geth-helm-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - geth
  - app
  - operator
  links:
  - name: Geth Helm Operator
    url: https://geth-helm-operator.domain
  maturity: alpha
  provider:
    name: liujinye
  version: 0.0.19
