# permissions for end users to view geths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: geth-viewer-role
rules:
- apiGroups:
  - charts.netwarps.com
  resources:
  - geths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.netwarps.com
  resources:
  - geths/status
  verbs:
  - get
